/* Project constants - action creators */
export const GET_LIST_PROJECT = "GET_LIST_PROJECT";
export const GET_LIST_PROJECT_CATEGORY = "GET_LIST_PROJECT_CATEGORY";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";

/* Project constants - async action */
export const CREATE_PROJECT_API = "CREATE_PROJECT_API";
export const GET_LIST_PROJECT_API = "GET_LIST_PROJECT_API";
export const GET_LIST_PROJECT_CATEGORY_API = "GET_LIST_PROJECT_CATEGORY_API";
export const EDIT_PROJECT_API = "EDIT_PROJECT_API";
export const DELETE_PROJECT_API = "DELETE_PROJECT_API";
export const ASSIGN_USER_PROJECT_API = "ASSIGN_USER_PROJECT_API";
export const REMOVE_USER_PROJECT_API = "REMOVE_USER_PROJECT_API";
export const GET_PROJECT_DETAIL_API = "GET_PROJECT_DETAIL_API";
