/* Task constants - action creators */
export const GET_LIST_STATUS_TASK = "GET_LIST_STATUS_TASK";
export const GET_LIST_PRIORITY_TASK = "GET_LIST_PRIORITY_TASK";
export const GET_LIST_TASK_TYPE = "GET_LIST_TASK_TYPE";
export const BY_MENU = "BY_MENU";
export const BY_PROJECT_DETAIL = "PROJECT_DETAIL";

export const EDIT_TASK = "EDIT_TASK";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const ADD_ASSIGNMENT = "ADD_ASSIGNMENT";
export const REMOVE_ASSIGNMENT = "REMOVE_ASSIGNMENT";
export const GET_ALL_COMMENT_TASK = "GET_ALL_COMMENT_TASK";
export const INSERT_COMMENT_TASK = "INSERT_COMMENT_TASK";
export const EDIT_COMMENT_TASK = "EDIT_COMMENT_TASK";
export const DELETE_COMMENT_TASK = "DELETE_COMMENT_TASK";
export const PUT_TASK_TYPE_DEFAULT = "PUT_TASK_TYPE_DEFAULT";
export const SET_VALUE_DEFAULT_CREATE_TASK = "SET_VALUE_DEFAULT_CREATE_TASK";
export const UNSET_VALUE_DEFAULT_CREATE_TASK =
  "UNSET_VALUE_DEFAULT_CREATE_TASK";
export const OPEN_CREATE_TASK = "OPEN_CREATE_TASK";

/* Task constants - async action */
export const GET_LIST_STATUS_TASK_API = "GET_LIST_STATUS_TASK_API";
export const GET_LIST_PRIORITY_TASK_API = "GET_LIST_PRIORITY_TASK_API";
export const GET_LIST_TASK_TYPE_API = "GET_LIST_TASK_TYPE_API";
export const CREATE_TASK_API = "CREATE_TASK_API";
export const GET_TASK_DETAIL_API = "GET_TASK_DETAIL_API";
export const UPDATE_TASK_API = "UPDATE_TASK_API";
export const DELETE_TASK_API = "DELETE_TASK_API";
export const GET_ALL_COMMENT_TASK_API = "GET_ALL_COMMENT_TASK_API";
export const INSERT_COMMENT_TASK_API = "INSERT_COMMENT_TASK_API";
export const EDIT_COMMENT_TASK_API = "EDIT_COMMENT_TASK_API";
export const DELETE_COMMENT_TASK_API = "DELETE_COMMENT_TASK_API";
